### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by mhoff** [team-pltb/pltb#1]

**Comment by stefanorf** [comment]
I did the review and changed some things. Please have a final look on my changes. And please read the last sentence, I don't really get it, if it is correct. After that, you can close this Issue.

**Comment by mhoff** [comment]
So with "last sentence" you refer to "As the pthread parallelization uses thread-to-core-pinning it is recommend to choose ((#processes - 1) \* #npthreads + 1) lower or equal the amount of cores to use."?
The point is, that when doing the model evaluation you have 1 master process and (#processes - 1) worker processes with #npthreads threads each.
The master process requires one core, as well as any worker thread (due to core pinning).
This leads to a total core usage of 1 + (#processes - 1) \* #npthreads.
Is this more clear now?

Another thing: Is the main title okay?

**Comment by stefanorf** [comment]
I think I got it. Can you please read the last sentence again and check if the changes I made are ok.

Main title: Maybe we could put the letters to which PLTB refers to in Uppercase?

**Comment by mhoff** [comment]
Checked and reintegrated (I had to overwrite your change).

Main title: Good point. And what do you think of "(evaluator)"?

**Comment by stefanorf** [comment]
"(evaluator)" fits!
Close this issue ;)
