### ISSUE TITLE
Model selection evaluation

### ISSUE THREAD

**Issue by mhoff** [team-pltb/pltb#5]
We established two new evaluation features:

```
./eval/calculate_distances.py hist-model eval/res/results/*/*.result
./eval/calculate_distances.py hist-model-per-ic eval/res/results/*/*.result
```

They generate the following data files:

```
$ ls eval/res/histograms/model_data/
aic  aiccc  aiccrc  bicc  bicrc  combined  overall
```

Using `gnuplot eval/models_per_ic_histogram.plot` the PDF `eval/res/histograms/plots/models_per_ic_histogram.pdf` can be generated (out of the data-file `combined`).
This PDF shows an overview over all models selected, how often they were selected and which IC has been the respective selector.
We think this figure is quite interesting.
@stamatak Please look into this figure and tell us what you think.

**Comment by stamatak** [comment]
thanks, this is indeed interesting, diego, we should consider adding 
this to the manuscript,

alexis

On 18.06.2015 08:29, Michael Hoff wrote:

> We established two new evaluation features:
> 
> |./eval/calculate_distances.py hist-model eval/res/results/_/_.result
> ./eval/calculate_distances.py hist-model-per-ic eval/res/results/_/_.result
> |
> 
> They generate the following data files:
> 
> |$ ls eval/res/histograms/model_data/
> aic  aiccc  aiccrc  bicc  bicrc  combined  overall
> |
> 
> Using |gnuplot eval/models_per_ic_histogram.plot| the PDF
> |eval/res/histograms/plots/models_per_ic_histogram.pdf| can be generated
> (out of the data-file |combined|).
> This PDF shows an overview over all models selected, how often they were
> selected and which IC has been the respective selector.
> We think this figure is quite interesting.
> @stamatak https://github.com/stamatak Please look into this figure and
> tell us what you think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/team-pltb/pltb/issues/5.

## 

Alexandros (Alexis) Stamatakis

Research Group Leader, Heidelberg Institute for Theoretical Studies
Full Professor, Dept. of Informatics, Karlsruhe Institute of Technology
Adjunct Professor, Dept. of Ecology and Evolutionary Biology, University
of Arizona at Tucson

www.exelixis-lab.org

**Comment by stefanorf** [comment]
Interestingly only 37 out of the 203 models are selected. This means that 165 models are not chosen at all!

Also maybe we should sort the data by models.

@stamatak Is it useful to extend the histogram by the 165 models that are not chosen? I discussed this with Michael, but he thinks that the models are not that correlated, so this would give use no useful information.

**Comment by stamatak** [comment]
On 18.06.2015 12:50, Stefan Orf wrote:

> Interestingly only 37 out of the 203 models are selected. This means
> that 165 models are not chosen at all!

even more interesting, I assume that this most somehow reflect the 
biological processes that are present ...

> Also maybe we should sort the data by models.
> 
> @stamatak https://github.com/stamatak Is it useful to extend the
> histogram by the 165 models that are not chosen? I discussed this with
> Michael, but he thinks that the models are not that correlated, so this
> would give use no useful information.

That's true, we should probably just show the 37 chosen ones, even the 
number 37 out of 203 is really already interesting ...

Cheers and thanks for all the additional work and interest in this.

Alexis

> —
> Reply to this email directly or view it on GitHub
> https://github.com/team-pltb/pltb/issues/5#issuecomment-113105540.

## 

Alexandros (Alexis) Stamatakis

Research Group Leader, Heidelberg Institute for Theoretical Studies
Full Professor, Dept. of Informatics, Karlsruhe Institute of Technology
Adjunct Professor, Dept. of Ecology and Evolutionary Biology, University
of Arizona at Tucson

www.exelixis-lab.org

**Comment by ddarriba** [comment]
I agree that we should add this figure. I noticed that among the 35 selected models, 8 belong to the so called GTR family of nested models: 012345 (GTR), 010232 (TIM2), 010212 (TPM2), 010020 (TrN), 012032 (TIM3), 012012 (TPM3), 010010 (HKY), 012314 (TVM). This means a 21.6% of the models, while this family comprises only 11 out of the 203 matrices (5.4%). They were selected on ~28.4%(AIC/AICc) to ~40.2% (BIC) of the evaluated samples.

So, according to these results it seems that BIC is more prompt to select the models in this family, even though GTR is less frequently selected than in AIC, but I don't see any particular reason for that. It could be just coincidence.

Also we can visualize in this figure how BIC and higher sample sizes tend to select less parameterized models, which is quite obvious looking at the BIC/AIC formulas, but here we can see the effect.

Thanks a lot!
